# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

resources:
  repositories:
  - repository: MyDocCollectionRepo
    type: github
    endpoint: herivelton-telefonica/doc-collection
    name: herivelton-telefonica/doc-collection
 
trigger:
- master

pool:
  vmImage: ubuntu-latest

- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run start-gendoc
  displayName: 'npm install and generate doc'

- checkout: MyDocCollectionRepo

- script: dir $(Build.SourcesDirectory)
- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: |
       swagger-output.json
    targetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy project files'

- task: PublishPipelineArtifact@1
  inputs:
    artifactName: apiDoc
    targetPath: '$(Build.ArtifactStagingDirectory)'
    publishLocation: 'pipeline'
  displayName: 'Publish npm artifact'